#!/usr/bin/env php
<?php

if (file_exists($composer = __DIR__ . '/../../autoload.php')) {
    require $composer;

    $cli = new Tonik\CLI\CLI(new League\CLImate\CLImate);

    return $cli->run(
        new Tonik\CLI\Renaming\Renamer(__DIR__),
        new Tonik\CLI\Scaffolding\Scaffolder(__DIR__)
    );
}

throw new Exception("Please, install composer dependences before running CLI.");
