#!/usr/bin/env php
<?php

if (file_exists($composer = __DIR__ . '/../../autoload.php')) {
    require $composer;

    $cli = new Tonik\CLI\CLI(new League\CLImate\CLImate);

    return $cli->run(
        new Tonik\CLI\Renaming\Renamer(dirname(__DIR__, 3)),
        new Tonik\CLI\Scaffolding\Scaffolder(dirname(__DIR__, 3))
    );
}

throw new Exception("Please, install composer dependences before running CLI.");
